### ISSUE TITLE
Can not access dashboard

### ISSUE THREAD

**Issue by thuansystemit** [bclozel/issues-dashboard#2]
Hi, I'm Thuan,

I have a problem when is run app
This is error when access dashboard after login:

```
Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.http.converter.HttpMessageConversionException: Type definition error: [simple type, class io.spring.demo.issuesdashboard.github.RepositoryEvent]; nested exception is com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `io.spring.demo.issuesdashboard.github.RepositoryEvent`, problem: 'comment_deleted' is not a valid event type
 at [Source: (PushbackInputStream); line: 1, column: 10786] (through reference chain: java.lang.Object[][1])] with root cause

java.lang.IllegalArgumentException: 'comment_deleted' is not a valid event type
	at io.spring.demo.issuesdashboard.github.RepositoryEvent$Type.valueFrom(RepositoryEvent.java:80) ~[classes/:na]
	at io.spring.demo.issuesdashboard.github.RepositoryEvent.<init>(RepositoryEvent.java:23) ~[classes/:na]
	at sun.reflect.GeneratedConstructorAccessor68.newInstance(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_144]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_144]
	at com.fasterxml.jackson.databind.introspect.AnnotatedConstructor.call(AnnotatedConstructor.java:124) ~[jackson-databind-2.9.2.jar:2.9.2]
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:274) ~[jackson-databind-2.9.2.jar:2.9.2]
```

Thanks and Regards,
Thuan Pham.

**Comment by bclozel** [comment]
Hi, sorry I didn't get back to you sooner - for some reason I didn't have notifications enabled on this repository.
This is now fixed (I've squashed the fix in the existing history to keep each step in order) - github recently introduced new events and I also forgot a few of those. I've added "comment_deleted" and "review_requested".

Thanks!
