### ISSUE TITLE
Exception while accessing over HTTPS on Java 9, Ubuntu 16.04.

### ISSUE THREAD

**Issue by icewheel** [bclozel/issues-dashboard#4]
I get this exception while accessing over HTTPS. I am running Ubuntu 16.04, Java 9 and Spring Boot v2.0.0.M7. Also installed library libtcnative-1. Also override the tomcat version in properties verion:

```
server.tomcat.version=9.0.1
tomcat.version=9.0.1
```

`2018-01-21 20:28:32.542 ERROR 9533 --- [  restartedMain] o.a.coyote.http11.Http11NioProtocol      : The upgrade handler [org.apache.coyote.http2.Http2Protocol] for [h2] only supports upgrade via ALPN but has been configured for the ["https-jsse-nio-8443"] connector that does not support ALPN.
`

```
java.lang.IllegalAccessException: class org.apache.tomcat.util.buf.ByteBufferUtils cannot access class jdk.internal.ref.Cleaner (in module java.base) because module java.base does not export jdk.internal.ref to unnamed module @76b1d6ab
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:361) ~[na:na]
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:589) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:556) ~[na:na]
	at org.apache.tomcat.util.buf.ByteBufferUtils.<clinit>(ByteBufferUtils.java:49) ~[tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.apache.tomcat.util.net.SocketBufferHandler.expand(SocketBufferHandler.java:155) [tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.apache.tomcat.util.net.SecureNioChannel.processSNI(SecureNioChannel.java:320) [tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.apache.tomcat.util.net.SecureNioChannel.handshake(SecureNioChannel.java:174) [tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1436) [tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.23.jar:8.5.23]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) [na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) [na:na]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.23.jar:8.5.23]
	at java.base/java.lang.Thread.run(Thread.java:844) [na:na]
```

**Comment by bclozel** [comment]
Hi, sorry I didn't get back to you sooner, I didn't have notifications enabled on this repository.

[According to the reference docs](https://docs.spring.io/spring-boot/docs/current/reference/html/howto-embedded-web-servers.html#howto-configure-http2-tomcat), you can use HTTP/2 with Tomcat in two ways.

With Tomcat 9+, by overriding the Tomcat version in your `pom.xml` and running the app with JDK9+

```xml
<properties>
    <tomcat.version>9.0.1</tomcat.version>
</properties>
```

With Tomcat 8.5 and libtcnative installed and provided to the JVM at startup (if the library is not installed in the native library path by default) - something like `-Djava.library.path=/usr/local/opt/tomcat-native/lib`

Did you follow those intructions?
